name: Bulk Delete Deployments
on: 
  workflow_dispatch: 

jobs:
  delete-deployments:
    runs-on: ubuntu-latest
    steps:
      - name: Clear all deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: '*' 
          onlyRemoveDeployments: true
